server:
  port: 8082

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://localhost:5432/user_management_db
    username: postgres
    password: Alex40021502

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    hostname: localhost         # explicitly set the hostname
    ip-address: 127.0.0.1         # use your machine's IP (in dev, often 127.0.0.1)
    prefer-ip-address: true       # tell Eureka to use the IP address rather than the hostname
    instance-id: ${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/