server:
  port: 8081

spring:
  application:
    name: FLIGHT-BOOKING-SERVICE

  datasource:
    url: jdbc:postgresql://localhost:5432/flight_booking_db
    username: postgres
    password: Alex40021502

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/